language: cpp

compiler:
  - gcc

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.14.0-rc4/cmake-3.14.0-rc4.tar.gz
  - tar -xvf cmake-3.14.0-rc4.tar.gz > /dev/null
  - mv cmake-3.14.0-rc4 cmake-install

  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .

script: ./bin/unit_tests
